### ISSUE TITLE
Windows launch discrepancies

### ISSUE THREAD

**Issue by robross0606** [AM2R-Community-Developers/AM2RLauncher#23]
If I launch AM2R.exe, I appear to get the old (pre-patched) version, but I can see my save games.  If click "Play" from AM2RLauncher, I get the updated patched version, but don't see any of my save games.  So:

1. Is there a way to Launch directly into the patched game without the two-step process of loading the launcher and then clicking "Play"?
2. How can I get the launcher to see my pre-existing save game data?

**Comment by Miepee** [comment]
1.  By opening `<AM2RLauncher Folder>/Profiles/Community Updates (Latest)/AM2R.exe` instead.

2. Not a launcher issue, expected behaviour. The Community Updates uses different save names. Open the AM2RLauncher, open the Mod Settings Tab, click on "Open Profile Save Directory", and rename `savX` to `saveX` with X being a number from 1-3.
Updating your saves like that may or may not guarantee without any issues.

**Comment by Lojemiru** [comment]
Saves will not be seen by the updated have regardless unless you rename them. Not recommended, but: Mod settings -> open save folder, rename savX files to saveX.

**Comment by robross0606** [comment]
Brilliant, thanks!
