### ISSUE TITLE
This game is not balanced. 

### ISSUE THREAD

**Issue by TylerHelt0** [AM2R-Community-Developers/AM2RLauncher#49]
Which one of you idiots decided the Core-X does not release green X when shot?

**Comment by Lojemiru** [comment]
Good afternoon sir!

I appreciate you taking the time out of your day to lodge an Official Complaint™️ with the AM2R Community Updates Developers™️. Unfortunately, I am afraid that we cannot act upon the Official Complaint™️ provided due to a number of factors.

First, I am afraid that this is not the correct repository for supplying us with Official Complaints™️ relating to the design of the game itself; this is the repository for the game launcher, which only handles patch and mod installation. I would, in other circumstances, redirect you to https://github.com/AM2R-Community-Developers/AM2R-Community-Updates instead, but we still have other factors to discuss.

Second, while we do employ idiots, I am afraid that we do not currently work with any idiot that you have described - nor have we in the past. The Core-X does indeed, contrary to your assumptions, spawn green X when shot. You may be experiencing the wrath of an entity known as "RNGsus"; I would advise that you take your complaints to the designers of pseudo-random number generation instead, in this scenario.

Finally, we are not in the habit of humoring Official Complaints™️ from individuals who bring an overly derogatory, brash, and ignorant attitude to our hallowed code repositories. I would advise that you try a different approach in the future in order to prevent scenarios such as this one from playing out again.

Kind regards,
Lojemiru
Chief Idiot of the AM2R Community Developers™️

**Comment by TylerHelt0** [comment]
Eat my poo
